service: serverless-azure-cosmosdb-crud

provider:
  name: azure
  runtime: nodejs12
  region: ${opt:region, 'West Europe'}
  stage: ${opt:stage, 'dev'}
  apim: true
  #type: Consumption # 'Developer', 'Standard', 'Premium', 'Basic', 'Consumption'

plugins:
  - serverless-azure-functions
  - serverless-webpack

package:
  exclude:
    - local.settings.json
    - .vscode/**

functions:
  create:
    handler: src/controllers/create.createController
    events:
      - http: true
        x-azure-settings:
          name: res
          methods: ['POST']
          authLevel: function
      - http: true
        x-azure-settings:
          name: $return
          direction: out
  read:
    handler: src/controllers/read.readController
    events:
      - http: true
        x-azure-settings:
          name: req
          methods: ['GET']
          authLevel: function
      - http: true
        x-azure-settings:
          name: $return
          direction: out
  update:
    handler: src/controllers/update.updateController
    events:
      - http: true
        x-azure-settings:
          name: req
          methods: ['PATCH']
          authLevel: function
      - http: true
        x-azure-settings:
          name: $return
          direction: out
  delete:
    handler: src/controllers/delete.deleteController
    events:
      - http: true
        x-azure-settings:
          name: req
          methods: ['DELETE']
          authLevel: function
      - http: true
        x-azure-settings:
          name: $return
          direction: out
